GET http://localhost:8080/target/user/all
###
POST http://localhost:8080/target/user/
Content-Type: application/json

{
  "name": "Samu",
  "email": "asd@asd.com"
}
###
GET http://localhost:8080/target/user/name/Samu
