POST http://localhost:8080/source/record

{ "module": "ProgBasics"}
###
POST http://localhost:8080/source/record

{
  "module": "ProgBasics",
  "mentor": "peter.szarka@codecool.com",
  "student": "foo@bar.com",
  "date": "2024-02-01",
  "cancelled": true,
  "comment": "Foo was sick."
}
###
POST http://localhost:8080/source/record

{ "module": "ProgBasics", "mentor": "peter.szarka@codecool.com", "student": "foo@bar.com", "date": "2024-02-05", "cancelled": false, "success": true, "comment": "Everything was ok.", "results": [{ "dimension": "Coding", "result": 80 }, { "dimension": "Communication", "result": 100}] }
###
POST http://localhost:8080/source/record

{ "module": "Web", "mentor": "mano.fabian@codecool.com", "student": "foo@bar.com", "date": "2024-05-11", "cancelled": false, "success": false, "comment": "Couldn't really start, just wrote some HTML.", "results": [{ "dimension": "Coding", "result": 0 }, {"dimension": "HTML", "result": 30}, {"dimension": "Communication", "result": 30}] }
###
POST http://localhost:8080/source/record

{
  "module": "Web",
  "mentor": "peter.szarka@codecool.com",
  "student": "foo@bar.com",
  "date": "2024-05-21",
  "cancelled": false,
  "success": false,
  "comment": "Wrote spaghetti code, and tried to sell it. Nice page, though.",
  "results": [
    { "dimension": "Coding", "result": 20 },
    {"dimension": "HTML", "result": 100},
    {"dimension": "Communication", "result": 80}
  ]
}
###
POST http://localhost:8080/source/record

{
  "module": "Web",
  "mentor": "peter.szarka@codecool.com",
  "student": "foo@bar.com",
  "date": "2024-06-01",
  "cancelled" : false,
  "success": true,
  "comment": "passed",
  "results": [
    { "dimension": "Coding", "result": 100 },
    { "dimension": "HTML", "result": 90 },
    { "dimension": "Communication", "result": 70 }
  ]
}
###
POST http://localhost:8080/source/record

{
  "module": "OOP",
  "mentor": "peter.szarka@codecool.com",
  "student": "foo@bar.com",
  "date": "2024-06-01",
  "cancelled" : false,
  "success": true,
  "comment": "passed2",
  "results": [
    { "dimension": "OOP", "result": 60 },
    { "dimension": "java", "result": 70 },
    { "dimension": "Communication", "result": 80 }
  ]
}
###
POST http://localhost:8080/source/record

{
  "module": "OOP",
  "mentor": "peter.szarka@codecool.com",
  "student": "foo@bar.com",
  "date": "2024-06-01",
  "cancelled" : false,
  "success": true,
  "comment": "passed3",
  "results": [
    { "dimension": "java", "result": 100 },
    { "dimension": "Communication", "result": 100 }
  ]
}
###
GET http://localhost:8080/source/record/all
###
POST http://localhost:8080/target/student
Content-Type: application/json

{
  "name": "Samu",
  "email": "foo@bar.com"
}
###
POST http://localhost:8080/target/student
Content-Type: application/json

{
  "name": "Nem Samu",
  "email": "notfoo@bar.com"
}
###
GET http://localhost:8080/target/student/all
###
GET http://localhost:8080/target/student/id/252
###
POST http://localhost:8080/target/mentor
Content-Type: application/json

{
  "name": "Szarka Péter",
  "email": "peter.szarka@codecool.com"
}
###
POST http://localhost:8080/target/mentor
Content-Type: application/json

{
  "name": "Fábián Manó",
  "email": "mano.fabian@codecool.com"
}
###
POST http://localhost:8080/copy
###
GET http://localhost:8080/statistics/average-result/student/email/foo@bar.com
###
GET http://localhost:8080/statistics/mentor-pass-rates


